content/urls.py

from django.urls import path

from . import views

app_name = "content"
urlpatterns = [
    # ex: /exam/
     path("", views.mainn, name = "main"),
     path("al/", views.load, name = "page"),
    # ex: /exam/result/
   
]

djangoweb/urls.py
from django.contrib import admin
from django.urls import path

from . import views
from . import htmlss

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.button),    
    path("youtubedownloader", views.exampage, name = "page"),
    path("youtubedownlofrader", views.answerpage, name = "anspage"),
    path("youtubedlofrader", views.login, name = "LOGIN"),
    path("youtubedlader", views.logn, name = "LOGN"),
    path("youtubedownader", views.signin, name = "SIGNIN")

]

exam/urls.py

from django.urls import path

from . import views

app_name = "exam"
urlpatterns = [
    # ex: /exam/
    path("", views.exampage, name = "exam"),

    # ex: /exam/result/
    path("result/", views.answerpage, name = "anspage"),
    #path("score/", views.core, name = "sco"),
    path("detailed/", views.danswerpage, name = "danss"),
   
]

trial/urls.py
from django.contrib import admin
from django.urls import include, path
from exam import views as user_view
from django.contrib.auth import views as auth

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("exam/", include("exam.urls")),
    path("content/", include("content.urls")),

    #path("q_enter/", include("q_enter.urls")),
    path("admin/", admin.site.urls),
    ##### user related path########################## 
    path('user/', include('user.urls')),
    #path("exam/<str:k>/", user_view.exampage, name = "exam"),

]

content/models.py
from django.db import models

# Create your models here.

content/views.py
import pandas as pd
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json
from django.shortcuts import render
import os
# Create your views here.

from user.models import use_info
from django.contrib.auth import get_user




def mainn(request):
    return render(request, 'content/main.html' )

@csrf_exempt

def load(request):
    global file_count
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            print(data)
            global nam
            nam = data.get('nam')
            # Process the data as needed
            response_data = {'status': 'success', 'aim_received': nam}
            print(nam)
            return JsonResponse(response_data)
        except json.JSONDecodeError:
            return JsonResponse({'status': 'error', 'message': 'Invalid JSON'}, status=400)    
    #nam="heat"    
    df=pd.read_excel("sample.xlsx")
    try:
        df_cleaned = df.dropna()
        conte= df_cleaned[nam].tolist()  
        print(len(conte))
        
    except KeyError:
        return render(request, 'content/main.html' )
    except NameError:
        return render(request, 'content/main.html' )    
    user = get_user(request)
    username = user.username
    if username=="":    
        print(username) 
        cat="null"
        cla="null"
        return render(request, 'content/page.html', {'max':json.dumps(conte), 'cate':cat, 'cla':cla } )
    else:
        blog = use_info.objects.get(username=username)
        cat= blog.category
        cla= blog.classs               
        scor= blog.score      
        print(scor)         
        return render(request, 'content/page.html', {'max':json.dumps(conte), 'cate':cat, 'cla':cla, 'score':scor } )

content/templates/content/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script type="text/javascript" id="MathJax-script" async
        src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js">
    </script>    
<style>
    .sticky1{
  position: sticky;
  top: 30%;
  background-color: #5b0000;
  padding: 4vw;
  rotate: 3deg;  
  margin-bottom: 2vw;
  z-index: 1;
  font-size: 1vw;
  font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;  
  }
  .sticky2{
  position: sticky;
  top: 30%;
  background-color: rgb(225, 3, 173);
  padding: 4vw;
  rotate: -3deg;  
  margin-bottom: 2vw;
  z-index: 1;  
  font-size: 1vw;
  font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;  
  }


  .bt{
    border: none;
    background-color: unset;
    border-radius: 10px;
    font-size: 2vw;
    font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;  
    color: seashell;
}  
article {
    text-align: center;
  background-image: linear-gradient(
    to bottom,
    transparent 50px,
    white 3 50px,
    #F5A623 calc(100% - 50px),
    transparent 0
  );
  z-index: 1;
  }

.container {
            display: flex;
            align-items: center;
            margin: 100px;
        }
.container img {
    max-width: 100px; /* Adjust as needed */
    margin-left: 20px; /* Space between image and text */
}
.navbar {
    overflow: hidden;
    background-color: azure;
    position: fixed; /* Set the navbar to fixed position */
    top: 0; /* Position the navbar at the top of the page */
    left: 0;
    width: 100%; /* Full width */
    z-index: 3;
    
    box-shadow: 0 4px 10px #0000001a;
}

/* Links inside the navbar */
.navbar a {
    float: left;
    display: block;
    color: #e62bf0;
    text-align: center;
    padding: 1.6%;
    text-decoration: none;
    font-size: 2vw;
    font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;    
}

/* Change background on mouse-over */
.navbar a:hover {
    background: whitesmoke;
    color: black;
    box-shadow: none;
}

/* Main content */
.main {
    margin-top: 50px; /* Add a top margin to avoid content overlay */
}
.bg{
    background-image: url("../../static/content/front.webp");

/* Set a specific height */
min-height: 700px; 
max-width: 100%;

/* Create the parallax scrolling effect */
background-attachment: fixed;
background-position: center;
background-repeat: no-repeat;
background-size: cover;
}
/* Turn off parallax scrolling for tablets and phones. Increase the pixels if needed */
@media only screen and (max-device-width: 1366px) {
  .bg {
    background-attachment: scroll;
  }
}
</style>
<body style="background-color: whitesmoke;">
    <div class="navbar">
        <a href="{% url 'content:main' %}">home</a>     
        <a href="{% url 'register' %}">Sign Up</a>            
    </div>  
    <div class="main">
        <div style="text-align: center;">
            <div class="bg"></div>
            <h1>Wlecome To </h1>
            <h4>Make Your Future In Your Dream Institutions</h4>
            <div>
                <h2>Sign Up and get started</h2>
            </div>              
        </div>    
        <div style="margin-top: 90px;text-align: center;">
            <h2>Browse Notes Now</h2>
        </div> 
        <div style=" display: grid;grid-template-columns: repeat(2, 1fr);grid-template-rows: repeat(4, 9vw);gap: 8vw;grid-template-areas:'sidebar1 sidebar2';">
            <div style="justify-self: self-end;">
            <article style="grid-area: sidebar1;">              
                <div  class="sticky2" >
                    <h3 style="float: left;">1...   </h3>
                    <a href="{% url 'content:page' %}"><button class="bt" onclick="cl(this.innerHTML)">Kinetic Theory of Gases</button></a>
                </div>
                <div  class="sticky1" >
                    <h3 style="float: left;">2...   </h3>
                    <a href="{% url 'content:page' %}"><button class="bt" onclick="cl(this.innerHTML)">heat and calorimatory</button></a>
                </div>
                <div  class="sticky2" >
                    <h3 style="float: left;">3...   </h3>
                    <a href="{% url 'content:page' %}"><button class="bt" onclick="cl(this.innerHTML)">Work,Energy and Power</button></a>
                </div> 
                <div  class="sticky1" >
                    <h3 style="float: left;">4...   </h3>
                    <a href="{% url 'content:page' %}"><button class="bt" onclick="cl(this.innerHTML)">System of Particles</button></a>
                </div>                     
            </article>
            </div>
            <div style="justify-self: self-start">
            <article style="grid-area: sidebar2;">
                <div  class="sticky2" >
                    <h3 style="float: left;">5...   </h3>
                    <a href="{% url 'content:page' %}"><button class="bt" onclick="cl(this.innerHTML)">Electrostatics</button></a>
                </div>
                <div  class="sticky1" >
                    <h3 style="float: left;">6...   </h3>
                    <a href="{% url 'content:page' %}"><button class="bt" onclick="cl(this.innerHTML)">Laws of Motion</button></a>
                </div>
                <div  class="sticky2">
                    <h3 style="float: left;">7...   </h3>
                    <a href="{% url 'content:page' %}"><button class="bt" onclick="cl(this.innerHTML)">COM & Momentum Conservation</button></a>
                </div>   
                <div  class="sticky1" >
                    <h3 style="float: left;">8...   </h3>
                    <a href="{% url 'content:page' %}"><button class="bt" onclick="cl(this.innerHTML)">Oscillation</button></a>
                </div>                   
            </article>              
            </div>
        </div>
        <div class="bg" style="min-height: 400px;"></div>
        <div style="text-align: center;">
            <h3>Loking for a place to practise questions, revise concepts Right Here!!</h3>
            <h2>SIGN up and get started</h2>
        </div>    
    </div>
    <div style="text-align: center;">
        <hr style="margin: 40px;">
        <footer>copyright</footer>
    </div> 
</body>

<script>

    function cl(val){
        
    
		var xhr = new XMLHttpRequest();

		// Configure it: POST-request for the URL
		xhr.open('POST', "{% url 'content:page' %}", true);

		// Set up the request headers
		xhr.setRequestHeader('Content-Type', 'application/json');
		xhr.setRequestHeader('X-CSRFToken', '{{ csrf_token }}');  // Ensure CSRF token is included

		// Send the request with the JSON data
		xhr.send(JSON.stringify({ 'nam': val}));
        localStorage.setItem("name", val);        	
        } 

</script>
</html>

content/templates/content/page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}
    <link rel="stylesheet" href="{% static 'content\style.css' %}">
    <title>Document</title>

    <script type="text/javascript">
        MathJax = {
            loader: {load: ['input/asciimath', 'output/chtml']},
            asciimath: {
                delimiters: [['`', '`']]  // Default delimiters for AsciiMath
            }
        };
    </script>
    <script type="text/javascript" async
        src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/startup.js">
    </script>

<style>
.navbar {
    overflow: hidden;
    background-color: azure;
    position: fixed; /* Set the navbar to fixed position */
    top: 0; /* Position the navbar at the top of the page */
    left: 0;
    width: 100%; /* Full width */
    z-index: 3;
    
    box-shadow: 0 4px 10px #0000001a;
}

/* Links inside the navbar */
.navbar a {
    float: left;
    display: block;
    color: #e62bf0;
    text-align: center;
    padding: 1.6%;
    text-decoration: none;
    font-size: 2vw;
    font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;    
}

/* Change background on mouse-over */
.navbar a:hover {
    background: whitesmoke;
    color: black;
    box-shadow: none;
}
span {
    font-family: Georgia, 'Times New Roman', Times, serif;
    font-size: 2vw;
    position: relative;

}
</style>
</head>

<body id="bdy"style="height: 100%;">
    {% load static %}
    <div id="bar" class="navbar" style="z-index: 3;box-shadow: 0 4px 10px #0000001a;">
        <a href="{% url 'content:main' %}">home</a>
        {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">Log Out</a>
        <a onclick="invert()">invert colors</a>
        <a style="color: aquamarine; float: right; margin-right: 20px;">Q~score  {{score}} </a>         
        <script>
            var isAuthenticated = true;
        </script>			
        {% else %}
        <a href="{% url 'login' %}" style="color: aquamarine; ">Q~score  {{score}} </a>  
        <a href="{% url 'register' %}">Sign Up</a>
        <a href="{% url 'login' %}">Log In</p></a>    
        <a id="invert">invert colors</a>
        <script>
            var isAuthenticated = false;
        </script>            
        {% endif %}           
    </div>  
   <div class="gr" style=" margin-top: 9vw;  display: grid;grid-template-columns: 1fr 4fr 1fr;grid-template-rows: repeat(3, 100px);gap: 10px;grid-template-areas:'sidebar1 content sidebar2';">
    <div style="grid-area: sidebar1;z-index: 1;"></div>
    <div style="grid-area: content;">

        
        <div>
            <div id="contentdiv"></div>
            <h2 id="trigger-element" style="margin-top: 100px;">chater contents</h2>
        </div>
    </div>
    <div id="popup" style="display: none;margin-left: 10%;grid-area: sidebar2; z-index: 1;">
        <p id="maxvalue" style="display: none;">{{max}}</p>
        <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">            
    </div>
</div>
  
</body>
<script>
  u = 0
  nu=0
  nuu=0
  po=150
  li_num=1
  chap_check=-1
  ran_check=-1
  img_num = 1
  x=null
  invert_colr = true

  
  document.getElementById("trigger-element").addEventListener("click", function() {
    document.getElementById("trigger-element").innerHTML="Load More"
    document.getElementById("popup").style.display = "inline-block";
    var myList = JSON.parse('{{ max|escapejs }}');
    console.log(myList);
   
    if(myList.length>nu){
        q = myList[nu]
        console.log(nu, "manfdan")
        if(q.includes("&image&")){
            console.log("alfred jeson")
            neww = q.split("&image&")
            var newElement = document.createElement("span");
            newElement.innerHTML=neww[u]
            newElement.style="white-space: pre-line"
            newElement.id="a"+ nuu 
            u++
            nuu++
            console.log(neww)
            document.getElementById("contentdiv").appendChild(newElement);     
            let image_name = localStorage.getItem("name");       
            for(;u<neww.length;u++, nuu++, img_num++){
                console.log("alfred jeson kaaaa")
                var neElement = document.createElement("img");
                //neElement.innerHTML = image_name+ img_num                                 
                neElement.src = "../../static/content/"+image_name+img_num+".png"
                neElement.style = "height:200px; width:300px"
                console.log(newElement.src+"alfrewgregwergwege")
                document.getElementById("contentdiv").appendChild(neElement);   
                var newElement = document.createElement("span");
                newElement.innerHTML=neww[u]
                newElement.style="white-space: pre-line; font-size: 2vw;   animation-name: flyin;animation-duration: 3s;  animation-delay: 2s;animation-fill-mode: backwards;     "
                console.log(u, neww[u], "aspertos", neww.length)
                newElement.id="a"+ nuu 
                var style = document.createElement('style');
                style.innerHTML = " @keyframes flyin {from {top: 200px;}to {top: 0px;}}"     
                // Append the <style> element to the document head
                document.head.appendChild(style);                   
                document.getElementById("contentdiv").appendChild(newElement);

            
            } 
            u=0 
        }else{
            console.log("kulfi", nu)
            var newElement = document.createElement("span");
            newElement.innerHTML=q
            newElement.style="white-space: pre-line;"
            newElement.id="a"+nuu
        }


        //newElement.style="display: block;background: url(../static/content/heat/heat"+ CSS.escape(nu) +".png) no-repeat scroll 0 0 rgba(0, 0, 0, 0);height:875px; width: 700px;"
        document.getElementById("contentdiv").appendChild(newElement);
        //document.getElementById("joke").innerHTML = "`x = (-b +- sqrt(b^2 - 4ac))/(2a)`"

        window.scrollBy({
                top: 600, // Adjust this value to scroll more or less
                behavior: 'smooth'
            });
        quest = ["check out these questions", "lost motive!! try these", "bulid confidence with these questions", "feel like you can't click me", "Wanan test yourself", "push betond time limits", "July"];
        if (isAuthenticated){
           quest_chap="{{cate}}"
        }else{
            quest_chap=["phyiscs", "chemistry", "maths"]
        }
        for( j=1; j<4 ; j++, li_num++, po=po+150){
            randomIndex = Math.floor(Math.random() * quest.length);
            ranquest = quest[randomIndex];
            console.log(randomIndex,ran_check,"frejuife")
            if(randomIndex==ran_check){
                console.log("alfred")
                randomIndex = Math.floor(Math.random() * quest.length);
                ranquest = quest[randomIndex];
            
                ran_check=randomIndex
                console.log(ran_check,"frefe")
            }
            ran_check=randomIndex
            
            randomIndex_chap = Math.floor(Math.random() * quest_chap.length);
            ranquest_chap = quest_chap[randomIndex_chap];
            //console.log(randomIndex,ran_check,"frejuife")
            if(randomIndex_chap==chap_check){
                console.log("alfred")
                randomIndex_chap = Math.floor(Math.random() * quest_chap.length);
                ranquest_chap = quest_chap[randomIndex_chap];
            
                chap_check=randomIndex_chap
                //console.log(ran_check,"frefe")
            }
            chap_check=randomIndex_chap
            final = ranquest+ " "+ ranquest_chap
            console .log(final ,"alfred")
            var newElement = document.createElement("form");
            //x="Gfag"
            newElement.action="{% url 'exam:exam' %}"
            newElement.method="GET"
            newElement.id="link"+li_num
            newElement.style="position: relative; top:"+ po +"px;   animation-name: example"+li_num+"; animation-duration: 4s;";
            document.getElementById("popup").appendChild(newElement);
            var style = document.createElement('style');
            style.innerHTML = " @keyframes example"+li_num+" {0%   {background-color:none; left:200px; top:"+ po +"px;}100% {background-color:none; left:0px; top:"+ po +"px;}}"     
            // Append the <style> element to the document head
            document.head.appendChild(style);   
            console.log(x, "aklfredc")
            var newElement = document.createElement("input");
            newElement.type="hidden"
            newElement.name="subject"
            newElement.value=x
            document.getElementById("link"+li_num).appendChild(newElement);
            var newElement = document.createElement("button");
            newElement.type="submit"
            newElement.style="border-radius: 10px; border-width: thick; border-color: darkcyan; color: darkcyan; font-size: 2vw; ";
            newElement.onclick=function() {extractq(this.innerHTML)};
            newElement.innerHTML=final;
            document.getElementById("link"+li_num).appendChild(newElement);
            }
        
        MathJax.typeset();   
        console.log("patyi", myList.length, nu)
    }else{
        document.getElementById("trigger-element").innerHTML="congrats you finished the chapter"
    }
    nu=nu+1; 
    nuu=nuu+1
    console.log(po,"afreeeeeeee")
    
  });
  //document.getElementById("trigger-element").click()

  function sendDataToDjango(x) {
    var data = {
        subject: x,
        csrfmiddlewaretoken: document.querySelector('[name=csrfmiddlewaretoken]').value
    };
    console.log("innn")
    fetch('http://127.0.0.1:8000/content/al/', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': data.csrfmiddlewaretoken
        },
        body: JSON.stringify(data)
    })
}

document.getElementById("invert").addEventListener("click", function() {
    if(invert_colr){
        document.getElementById("bdy").style = "background-color:rgb(24, 22, 22); color: white;"
        document.getElementById("invert").style = "black"
        document.getElementById("bar").style.backgroundColor = "rgb(24, 22, 22)"
        document.getElementById("bar").style.boxShadow = "0 4px 10px #fff8f8"
        invert_colr= false
    }else{
        document.getElementById("bdy").style = "background-color; white; color: black;"
        document.getElementById("invert").style.ba = "white"
        document.getElementById("bar").style.backgroundColor = "azure"
        document.getElementById("bar").style.boxShadow = "0 4px 10px #0000001a"
        invert_colr= true
    }      
            
        });


 function extractq(value){
    alert("fetching questions")
    for (let item of quest) {
        console.log(item , value);
        if (value.includes(item)){
        x=value.replace(item, "")
        console.log(x, "Gsgs") 
        sendDataToDjango(x)
        document.querySelector('input').value=x
        return x
    }
    
    }
    console.log("success")
    //console.log(document.getElementById("test").innerHTML);
    //diction=document.getElementById("test").innerHTML;
    //diction=diction.split("', '");
    //console.log(diction[3]);
    //localStorage.setItem("diction", diction);
}
isAuthenticated
</script>
</html>