content/urls.py

from django.urls import path

from . import views

app_name = "content"
urlpatterns = [
    # ex: /exam/
     path("", views.mainn, name = "main"),
     path("al/", views.load, name = "page"),
    # ex: /exam/result/
   
]

djangoweb/urls.py
from django.contrib import admin
from django.urls import path

from . import views
from . import htmlss

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.button),    
    path("youtubedownloader", views.exampage, name = "page"),
    path("youtubedownlofrader", views.answerpage, name = "anspage"),
    path("youtubedlofrader", views.login, name = "LOGIN"),
    path("youtubedlader", views.logn, name = "LOGN"),
    path("youtubedownader", views.signin, name = "SIGNIN")

]

exam/urls.py

from django.urls import path

from . import views

app_name = "exam"
urlpatterns = [
    # ex: /exam/
    path("", views.exampage, name = "exam"),

    # ex: /exam/result/
    path("result/", views.answerpage, name = "anspage"),
    #path("score/", views.core, name = "sco"),
    path("detailed/", views.danswerpage, name = "danss"),
   
]

trial/urls.py
from django.contrib import admin
from django.urls import include, path
from exam import views as user_view
from django.contrib.auth import views as auth

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("exam/", include("exam.urls")),
    path("content/", include("content.urls")),

    #path("q_enter/", include("q_enter.urls")),
    path("admin/", admin.site.urls),
    ##### user related path########################## 
    path('user/', include('user.urls')),
    #path("exam/<str:k>/", user_view.exampage, name = "exam"),

]

exam/models.py
from django.db import models

# Create your models here.



class phy_easy(models.Model):
    classs = models.IntegerField(default=0)
    category = models.TextField(default='none')
    chapter = models.TextField(default='none')
    option1 = models.TextField(default='none')
    option2 = models.TextField(default='none')
    option3 = models.TextField(default='none')
    option4 = models.TextField(default='none')
    question = models.TextField(default='none')
    question_img = models.TextField(default='none')
    answer = models.TextField(default='none')
    danswer = models.TextField(default='none')
    danswer_img = models.TextField(default='none')
    def __str__(self):
        return self.question

exam/views.py
from django.contrib.auth import get_user
from django.shortcuts import render, get_object_or_404
import sqlite3, random,json
from random import randint
from django.core.exceptions import ObjectDoesNotExist

from .models import phy_easy
from user.models import use_info


from django.db.models import Count
# Create your views here.
def exampage(request):
    print(request)
    subject = request.POST.get('subject')
    if subject==None:
        print("nione")
    print(5, subject)
    i=1
    # Iterate through the dictionary and add each item to the array
    #row = phy_easy.objects.get(id=1)
    count = phy_easy.objects.aggregate(count=Count('id'))['count']
    random_index = randint(0, count - 1)
    print(phy_easy.objects.all()[random_index])
    x=[]
    global dans
    dans=[]
    k=0
    while i<3:
        random_index = randint(0, count - 1) 
        if random_index==k:
            random_index = randint(0, count - 1) 

        k=random_index
        print("not equal")
        row = phy_easy.objects.all()[random_index]
        print(row.question)
        x.append(row.question)
        x.append(row.option1)
        x.append(row.option2)
        x.append(row.option3)
        x.append(row.option4)
        x.append(row.answer)
        if row.danswer==None:
            dans.append(row.danswer_img)
        else:
            dans.append(row.danswer)
        i=i+1    
    print(x)
    x=str(x)
    x=x.replace("['", "")
    x=x.replace("']", "")
    #x="jeson', 'e', 'f', 'g', 'h', 'e', 'alfred', 'a', 'b', 'c', 'd', 'd', 'alfredoooo', 'aa', 'ba', 'cc', 'dd', 'cc', 'jesonnnnnn', 'e', 'ff', 'gg', 'hh', 'ee"
    return render(request, "exam/exam.html", {"ti": x, 'dans':json.dumps(dans)})

def answerpage(request):
    if request.method == 'POST':
        print(request)
        data = json.loads(request.body)
        item1 = data.get('item1')
        print(item1)     
        user = get_user(request)
        username = user.username    
        print(username)    
        blog = use_info.objects.get(username=username)     
        print(blog)
        blog.score=int(blog.score)+int(item1)  
        blog.save()
        blog = use_info.objects.get(username=username)  
        h=blog.score
        print(h)   
    return render(request, 'exam/answerpg.html', {'score':'h'})


def danswerpage(request):
    try:
        user = get_user(request)
        username = user.username            
        blog = use_info.objects.get(username=username)     
        print(blog)        
        return render(request, 'exam/detailans.html', {'dans':json.dumps(dans), 'score':blog.score} )
    except use_info.DoesNotExist:
        print("advertisment")
        return render(request, 'exam/detailans.html', {'dans':json.dumps(dans), 'lo': "please login to save your score"})

exam/templates/exam/answerpg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
<link rel="stylesheet" href="{% static 'exam\style.css' %}">    
    <script type="text/javascript" id="MathJax-script" async
        src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js">
    </script>
<style>
      /* The navigation bar */
.navbar {
    overflow: hidden;
    background-color: #333;
    position: fixed; /* Set the navbar to fixed position */
    top: 0; /* Position the navbar at the top of the page */
    width: 100%; /* Full width */
}

/* Links inside the navbar */
.navbar a {
    float: left;
    display: block;
    color: #f2f2f2;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

/* Change background on mouse-over */
.navbar a:hover {
    background: #ddd;
    color: black;
}
</style>
</head>

<body onload="noBack()" onpageshow="if (event.persisted) noBack();">
    <div class="navbar">
        <a href="{% url 'content:main' %}">home</a>
       {% if user.is_authenticated %}
       <a href="{% url 'logout' %}">Log Out</a>
       <a style="color: aquamarine; float: right; margin-right: 20px;">Q~score  {{score}} </a>         
       <script>
           var isAuthenticated = true;
       </script>			
       {% else %}
       <a href="{% url 'login' %}" style="color: aquamarine; ">Q~score  {{score}} </a>  
       <a href="{% url 'register' %}">Sign Up</a>
       <a href="{% url 'login' %}">Log In</p></a>        
       <script>
           var isAuthenticated = false;
       </script>            
       {% endif %}           
    </div>    
    <div style="background-color: cornsilk; width: 600px; height: 500px; margin: 30%; margin-top: 10%; text-align: center; padding: 40px;">
        <h2 id="sco">Your score</h2>
        <div style="margin-top: 10%; margin-left: 5%; width: 500px; display: grid;   grid-template-columns: repeat(2, 1fr);grid-template-rows: repeat(1, 100px);">    
            <h3 id="cor" >no of correct</h3>
            <h3 id="incor" >no of incorrect</h3>            
        </div>
        <div>
            {% if user.is_authenticated %}			
            {% else %}
            <h1 id="nof" >login to save your score</h1>
            {% endif %}  
            <a href="{% url 'exam:exam' %}"><h3 >go for another pentagon(5 questions)</h3></a>
            <h3>check out this 10 questions</h3>
            <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">            
            <a href="{% url 'exam:danss' %}"><h3>detailed answer</h3></a>
            <p>
                 \[
                 n = \frac{m}{M}
                 \]
                 
                 \[
                 PV = \frac{m}{M} RT
                 \]
                 
                 \[
                 P = \frac{m}{VM} RT
                 \]
                 
                 \[
                 P = \frac{\rho RT}{M}
                 \]                 
                When \(a \ne 0\), there are two solutions to \(ax^2 + bx + c = 0\) and they are
                $$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$
                \[ A_{f} = A \cdot (1 - \beta \cdot \Delta \cdot T)^{-1} = A(1 - \beta \cdot \Delta \cdot T) \]
                \begin{equation}
4F ^ 2 + 9F ^ 2 + 12F ^ 2 \cdot \cos(\theta) = R ^ 2 
\end{equation}

\begin{align*}
\vec{r}_s &= \frac{a}{2}\hat{i} + \frac{a}{2}\hat{k} \\
\vec{r}_H &= \frac{a}{2}\hat{j} + \frac{a}{2}\hat{k} \\
\vec{r}_H - \vec{r}_s &= \frac{a}{2} (\hat{j} - \hat{i})
\end{align*}
\begin{equation} 
\Delta T = 0
\Delta T=0 \ce{2 H2O}
\end{equation}
\textbf{Charles and Gay-Lussac Law}

We find that when the pressure is held constant, the volume is proportional to the temperature. This statement is the law of Charles and Gay-Lussac. This can be expressed mathematically as:
\[\frac{V_{1}}{V_{2}} = \frac{T_{1}}{T_{2}}\]
\[\frac{V_{1}}{T_{1}} = \frac{V_{2}}{T_{2}}\]
\[\frac{V}{T} = \text{constant}\]

As with Boyle's law, the amount of gas also must be held constant for the equation.

\textbf{Ideal Gas Law}

Boyle’s law and the law of Charles and Gay-Lussac are particular cases of a more general expression called the "ideal gas law". It can be written as: \(PV=nRT\)

\[\frac{P_{1}V_{1}}{T_{1}} = \frac{P_{2}V_{2}}{T_{2}} \text{ As number of moles in initial and final state are equal}\]

The amount of a gas is generally measured in moles, given as \(n\). A mole (mol) is the amount of material whose mass in grams is numerically equal to the molecular mass of the substance. For example, the molecular mass of \(O_{2}\) is 32, thus a mole of oxygen is 32 grams.

\textbf{Avogadro's Number and Avogadro Hypothesis}

Avogadro stated that equal volumes of gas at the same pressure and temperature contain equal numbers of molecules. This statement is called Avogadro's hypothesis. We can see that this statement is consistent with \(R\) being the same for all gases.

\[N_{A} = 6.023 \times 10^{23} \text{ molecules/mole}\]

Thus, in \(n\) moles of a gas, the total number of molecules of the gas is:
\[N = nN_{A}\]

or the number of moles of a gas can be given as \(n = N/N_{A} = (m' \times N)/(m' \times N_{A}) = m/M\)

Here, \(m'\) is the mass of each molecule, \(m\) is the total mass of the gas and \(M\) is the mass of 1 mole of molecules of gas (i.e. its molecular mass).

From the gas law, we have:
              </p>
        </div>
    </div>    
</body>
<script src="https://cdn.jsdelivr.net/npm/crypto-js@4.1.1/crypto-js.js"></script>

<script>
    //encrypt

console.log(localStorage.getItem("hasRun"))


  
    window.history.forward();
    function noBack() {
        window.history.forward();
    }

    givenans=[]
    correct=0
    wrong=0
    var score=0
    const storedJsonString = localStorage.getItem('gans');
    const bytes = CryptoJS.AES.decrypt(storedJsonString, "secret key 123");
    console.log(bytes)
    var givnans = bytes.toString(CryptoJS.enc.Utf8);  
    givnans=JSON.parse(givnans) 
    console.log(givnans) 
    for (const key in givnans) {
    const value = givnans[key];
    givenans.push(value)
    console.log(`Key: ${key}, Value: ${value}`);
}
    const storedArrayString = localStorage.getItem("ans");
    const byte = CryptoJS.AES.decrypt(storedArrayString, "secret key 123");
    var ans = byte.toString(CryptoJS.enc.Utf8);
    ans=JSON.parse(ans)     

    //console.log(`Decrypted Data: ${decryptedData}`);     

    //let ans = localStorage.getItem("answer");
    console.log(typeof(ans))
    for(i=0;i<givenans.length; i++){
        an=ans[i]
        gi=givenans[i]
        console.log(an,gi)
        if (an==gi && gi!='undefined'){
            correct=correct+1
            score=score+4
        }else{
            score=score-1
            wrong=wrong+1
        }
    }

document.getElementById("sco").innerHTML="Your Score: "+score
document.getElementById("cor").innerHTML="no of correct: "+correct
document.getElementById("incor").innerHTML="no of incorrect: "+wrong

function sendDataToDjango() {   
    var data = {
        item1: score,
        csrfmiddlewaretoken: document.querySelector('[name=csrfmiddlewaretoken]').value
    };
    console.log("innn")
    fetch('http://127.0.0.1:8000/exam/result/', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': data.csrfmiddlewaretoken
        },
        body: JSON.stringify(data)
    })
}
if (localStorage.getItem('hasRun')=='false') {
    sendDataToDjango()
    console.log("Function is running");
    localStorage.setItem('hasRun', 'true');
}

</script>
</html>

exam/templates/exam/detailans.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'exam/style.css' %}">   
    <script type="text/javascript" id="MathJax-script" async
        src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js">
    </script>      
<style>
      /* The navigation bar */
.navbar {
    overflow: hidden;
    background-color: #333;
    position: fixed; /* Set the navbar to fixed position */
    top: 0; /* Position the navbar at the top of the page */
    width: 100%; /* Full width */
}

/* Links inside the navbar */
.navbar a {
    float: left;
    display: block;
    color: #f2f2f2;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

/* Change background on mouse-over */
.navbar a:hover {
    background: #ddd;
    color: black;
}
</style>
</head>
<body onload="noBack()" onpageshow="if (event.persisted) noBack();">
    <div class="navbar">
        <a href="{% url 'content:main' %}">home</a>
        {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">Log Out</a>
        <a style="color: aquamarine; float: right; margin-right: 20px;">Q~score  {{score}} </a>         
        <script>
            var isAuthenticated = true;
        </script>			
        {% else %}
        <a href="{% url 'login' %}" style="color: aquamarine; ">Q~score  {{score}} </a>  
        <a href="{% url 'register' %}">Sign Up</a>
        <a href="{% url 'login' %}">Log In</p></a>        
        <script>
            var isAuthenticated = false;
        </script>            
        {% endif %}          
    </div>  
    <div style="margin-top: 82px;">
        <h1>{{lo}}</h1>
        
        <div id="main"></div>
    </div>

</body>
<script src="https://cdn.jsdelivr.net/npm/crypto-js@4.1.1/crypto-js.js"></script>

<script>
    givenans=[]
    correct=0
    wrong=0
    score=0
    const storedJsonString = localStorage.getItem('gans');
    const bytes = CryptoJS.AES.decrypt(storedJsonString, "secret key 123");
    var givnans = bytes.toString(CryptoJS.enc.Utf8);    
    givnans=JSON.parse(givnans)
    for (const key in givnans) {
    const value = givnans[key];
    givenans.push(value)
    console.log(`Key: ${key}, Value: ${value}`);
}    

    const storedArrayString = localStorage.getItem("ans");
    const byte = CryptoJS.AES.decrypt(storedArrayString, "secret key 123");
    var ans = byte.toString(CryptoJS.enc.Utf8);
    ans=JSON.parse(ans)

    var dans = JSON.parse('{{ dans|escapejs }}');


    const storedArrayStri = localStorage.getItem("quest");
    const by = CryptoJS.AES.decrypt(storedArrayStri, "secret key 123");
    var question = by.toString(CryptoJS.enc.Utf8); 
    question=JSON.parse(question)

    const storedArrayStr = localStorage.getItem("opt");
    const b = CryptoJS.AES.decrypt(storedArrayStr, "secret key 123");
    var option = b.toString(CryptoJS.enc.Utf8);     
    option=JSON.parse(option)
     console.log(question,option, givenans, ans)
    for(r=0,k=0;r<ans.length;k=k+4, r++){
        console.log("akfrej")
        console.log(option[r])
        var newElement = document.createElement("h2");
        newElement.innerHTML=question[r]
        document.getElementById("main").appendChild(newElement); 

        var newElement = document.createElement("h3");
        newElement.innerHTML=option[k]
        document.getElementById("main").appendChild(newElement);         
        var newElement = document.createElement("h3");
        newElement.innerHTML=option[k+1]
        document.getElementById("main").appendChild(newElement);        
        var newElement = document.createElement("h3");
        newElement.innerHTML=option[k+2]
        document.getElementById("main").appendChild(newElement);        
        var newElement = document.createElement("h3");
        newElement.innerHTML=option[k+3]
        document.getElementById("main").appendChild(newElement);        
        
        var newElement = document.createElement("h3");
        newElement.innerHTML="your answer: "+givenans[r]
        document.getElementById("main").appendChild(newElement); 
        var newElement = document.createElement("h3");
        newElement.innerHTML="correct answer: "+ans[r]
        document.getElementById("main").appendChild(newElement);      

        var newElement = document.createElement("h2");
        newElement.innerHTML="detailed answer"
        document.getElementById("main").appendChild(newElement);                        

        var newElement = document.createElement("h3");
        newElement.innerHTML=dans[r]
        document.getElementById("main").appendChild(newElement);                        
    }

</script>
</html>